#pragma config(Hubs,  S1, HTServo,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S2,     backLightSensor,     sensorLightActive)
#pragma config(Sensor, S3,     frontLightSensor,    sensorLightActive)
#pragma config(Sensor, S4,     distanceSensor,      sensorSONAR)
#pragma config(Motor,  motorA,          boxDoor,       tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     rightWheel,    tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     leftWheel,     tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     rightOmniWheel, tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     leftOmniWheel, tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     belt,          tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_2,     scoringBox,    tmotorNormal, openLoop)
#pragma config(Servo,  srvo_S1_C1_1,    bridgeServo,          tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    scoreBoxTilt,         tServoStandard)
#pragma config(Servo,  srvo_S1_C1_3,    dispenserDoor,        tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#ifndef MOTORS
#include "motorsSensors.h"
#endif
#ifndef CONST
#include "constants.h"
#endif
#ifndef HI
#include "highLevelMoves.c"
#endif

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.

void balanceOnBridgeFromLeft();
void gotoMiddleDispenserFromRight();

void initializeRobot()
{
  bFloatDuringInactiveMotorPWM = false;  // brake
  initializeServos();
  disableDiagnosticsDisplay();
  return;
}

task main()
{
  initializeRobot();

  //sensorsDebug(true);

  waitForStart();

  //balanceOnBridgeFromLeft();

  gotoMiddleDispenserFromRight();
}

void balanceOnBridgeFromLeft(){
  moveStraight(DIR_FWD, 63, 1800, false);//move forward from box at right

  turn(TURN_RIGHT, 24, 900);

  moveStraightUntilLine(DIR_FWD, 0, 0, false);

  hitLineTurningRight(800);

  moveStraight(DIR_BACK, 0, 1000, false);//now we are at the bridge

  moveStraight(DIR_FWD, 0, 200, false);//now we are at the bridge

  putDownBridge();

  wait10Msec(50);

//  moveStraight(DIR_BACK, 0, 1000, false);
  moveStraight(DIR_BACK, 170, 1300, true);
  moveStraight(DIR_BACK, 167, 250, false);

  putDownBridge(false);
}

void gotoMiddleDispenserFromRight(){
  moveStraight(DIR_FWD, 63, 1300, false);//move forward from box at right

  turn(TURN_LEFT, 24, 900);

  moveStraightUntilLine(DIR_FWD, 0, 0, false);

  hitLineTurningLeft(800);

  moveStraight(DIR_BACK, 0, 1000, false);//now we are at the bridge

  moveStraight(DIR_FWD, 0, 200, false);//now we are at the bridge

  putDownBridge();

  wait10Msec(150);

  moveStraight(DIR_BACK, 0, 1000, false);

  scoreOnStat();

  putDownBridge(false);

  moveStraight(DIR_BACK, 70, 2000, false);

  turn(TURN_RIGHT, 0, 500);

  turn(TURN_RIGHT, 75, 200);

  moveStraight(DIR_FWD, 0, 1000, false);

  moveStraightUntilLine(DIR_FWD, 190, 0, false);

  //moveStraight(DIR_BACK, 0, 150, false);

  //hitLineTurningRight(800);

  turn(TURN_RIGHT, 0, 1050);

  //attempts at self-correcting; rather hackish and should not be used

  //swing(DIR_FWD | TURN_LEFT, 0, 300);

  //turn(TURN_LEFT, 0, 100);

  moveStraight(DIR_FWD, 0, 1500, false);

  moveStraight(DIR_BACK, 0, 250, false);//align with dispenser

  do{

    dispenseFromTop();

    /*if(random(1)==1)
      turn(TURN_LEFT, 0, 100);
    else*/
      turn(TURN_RIGHT, 0, 100);

    if(random(1)==1)
      dispenseFromTop();

  }while(true);
}
