#pragma config(Hubs,  S1, HTServo,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S2,     backLightSensor,     sensorLightActive)
#pragma config(Sensor, S3,     frontLightSensor,    sensorLightActive)
#pragma config(Sensor, S4,     distanceSensor,      sensorSONAR)
#pragma config(Motor,  motorA,          boxDoor,       tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     rightWheel,    tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     leftWheel,     tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     rightOmniWheel, tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     leftOmniWheel, tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     motorH,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     motorI,        tmotorNormal, openLoop)
#pragma config(Servo,  srvo_S1_C1_1,    bridgeServo,               tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    scoreBoxTilt,                  tServoStandard)
#pragma config(Servo,  srvo_S1_C1_3,    dispenserDoor,                 tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#ifndef MOTORS
#include "motorsSensors.h"
#endif
#ifndef CONST
#include "constants.h"
#endif
#ifndef HI
#include "highLevelMoves.c"
#endif

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.


void initializeRobot()
{
  initializeServos();
  disableDiagnosticsDisplay();
  return;
}

task main()
{
  initializeRobot();

  //sensorsDebug(true);

  moveStraight(DIR_FWD, 63, 1800, false);//move forward from box at right

  turn(TURN_LEFT, 24, 900);

  moveStraightUntilLine(DIR_FWD, 0, 0, false);

  hitLineTurningLeft(800);

  moveStraight(DIR_BACK, 0, 1000, false);//now we are at the bridge

  moveStraight(DIR_FWD, 0, 200, false);//now we are at the bridge

  putBridgeDown();

  wait10Msec(50);

//  moveStraight(DIR_BACK, 0, 1000, false);
  moveStraight(DIR_BACK, 170, 1300, true);
  moveStraight(DIR_BACK, 167, 250, false);

  putBridgeUp();

  moveStraight(DIR_BACK, 70, 2000, false);

  turn(TURN_RIGHT, 0, 380);

  moveStraight(DIR_FWD, 0, 800, false);

  moveStraightUntilLine(DIR_FWD, 190, 0, false);

  hitLineTurningRight(1500);

  //swing(DIR_FWD | TURN_LEFT, 0, 300);

  turn(TURN_LEFT, 0, 100);

  moveStraight(DIR_FWD, 0, 1500, false);

  //sensorsDebug(true);

  //moveStraightUntilLine(DIR_BACK, 0, 0, 0);

  //sensorsDebug(true);

  //alignWithNextLine(DIR_FWD);

  //sensorsDebug();

  /* test code:
    nMotorEncoderTarget[Belt]=-2280;
  motor[Belt]=-40;

  wait10Msec(500);
  motor[Belt]=0;

  nMotorEncoderTarget[Belt]=2280;
  motor[Belt]=40;

  wait10Msec(500);
  motor[Belt]=0;

  return;

  */
}
