#pragma config(Hubs,  S1, HTServo,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S2,     backLightSensor,     sensorLightActive)
#pragma config(Sensor, S3,     frontLightSensor,    sensorLightActive)
#pragma config(Sensor, S4,     distanceSensor,      sensorSONAR)
#pragma config(Motor,  motorA,          boxDoor,       tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     rightWheel,    tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     leftWheel,     tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     rightOmniWheel, tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     leftOmniWheel, tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     belt,          tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_2,     scoringBox,    tmotorNormal, openLoop)
#pragma config(Servo,  srvo_S1_C1_1,    bridgeServo,          tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    scoreBoxTilt,         tServoStandard)
#pragma config(Servo,  srvo_S1_C1_3,    dispenserDoor,        tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){
  motor[rightWheel]=motor[leftWheel]=motor[rightOmniWheel]=motor[leftOmniWheel]=-100;

  do{
    if(SensorValue[distanceSensor]!=255){
      motor[leftWheel]=motor[leftOmniWheel]=0;
      wait10Msec(100);
    }else
      motor[leftWheel]=motor[leftOmniWheel]=-100;
    wait1Msec(100);
  }while(SensorValue[distanceSensor]>20);

  motor[rightWheel]=motor[leftWheel]=motor[rightOmniWheel]=motor[leftOmniWheel]=-50;

  wait10Msec(50);

  motor[rightWheel]=motor[leftWheel]=motor[rightOmniWheel]=motor[leftOmniWheel]=0;
}
