#pragma config(Hubs,  S1, HTServo,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S2,     backLightSensor,     sensorLightActive)
#pragma config(Sensor, S3,     frontLightSensor,    sensorLightActive)
#pragma config(Sensor, S4,     distanceSensor,      sensorSONAR)
#pragma config(Motor,  motorA,          boxDoor,       tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorB,          LeftHook,      tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorC,          RightHook,     tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     rightWheel,    tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     leftWheel,     tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     rightOmniWheel, tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     leftOmniWheel, tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     belt,          tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_2,     scoringBox,    tmotorNormal, openLoop)
#pragma config(Servo,  srvo_S1_C1_1,    bridgeServo,          tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    scoreBoxTilt,         tServoStandard)
#pragma config(Servo,  srvo_S1_C1_3,    dispenserDoor,        tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"


task main(){
  int l=0, r=0;
  int i1, i2;
  int delta;
  do{
    getJoystickSettings(joystick);
    if(abs(joystick.joy1_y1) > 10)
      delta = sgn(joystick.joy1_y1);
    else
      delta = 0;
    l += delta;
    if(abs(joystick.joy1_y2) > 10)
      delta = sgn(joystick.joy1_y2);
    else
      delta = 0;
    r += delta;
    motor[rightWheel] = r;
    motor[rightOmniWheel] = r;
    motor[leftWheel] = l;
    motor[leftOmniWheel] = l;
    wait10Msec(1);
  }while(true);
}
