#pragma config(Motor,  motorA,          turn,          tmotorNormal, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){
  int speed = 0;

  do{
    motor[turn]=speed;
    if(nNxtButtonPressed==1&&speed<100)
      speed++;
    if(nNxtButtonPressed==2&&speed>-100)
      speed--;
    if(nNxtButtonPressed==3)
      speed=-speed;
    nxtDisplayTextLine(1, "%d", speed);
    wait10Msec(10);
  }while(true);
}
