#pragma config(Motor,  motorA,          door,          tmotorNormal, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){
  nMotorEncoderTarget[door]=100;
  motor[door]=50;
  wait10Msec(100);
  motor[door]=0;
  wait10Msec(100);
  nMotorEncoderTarget[door]=100;
  motor[door]=-50;
  wait10Msec(100);
  motor[door]=0;
}
